#C1
correct.number=100
max.attempts=5

#C2
range1.max=100
range1.price=1000

range2.max=150
range2.price=1500

range3.price=2000

#C3
array=1,5,7,4,6,8,4,7,8,3

#C4
url=jdbc:oracle:thin:@//localhost:1521/xe
username=student
password=student123
